AdventOne/Models/Attachment.cs
using System.ComponentModel.DataAnnotations;

namespace AdventOne.Models {

    public enum FileType {
        Quotation = 1,
        PurchaseOrder
    }

    public class Attachment {

        public int ID { get; set; }
        [StringLength(255)]
        public string FileName { get; set; }
        [StringLength(255)]
        [Required]
        public string Description { get; set; }
        [StringLength(100)]
        public string ContentType { get; set; }
        public byte[] Content { get; set; }
        public FileType FileType { get; set; }
        public int ProjectId { get; set; }

        public virtual Project Project { get; set; }

    }
}

AdventOne/Models/Invoice.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AdventOne.Models {

    public class Invoice {

        public int ID { get; set; }
        public int ProjectID { get; set; }

        [EnumDataType(typeof(InvoiceStatus))]
        public InvoiceStatus Status { get; set; }

        public String InvoiceNumber { get; set; }

        public DateTime InvoiceDate { get; set; }
        public DateTime DueDate { get; set; }
        public DateTime ExpectedPaymentDate { get; set; }
        public int DaysOverdue { get; set; }


        [Range(0, 10000000000)]
        [DataType(DataType.Currency)]
        public decimal Amount { get; set; }

        public virtual Project Project { get; set; }
        public virtual ICollection<InvoiceNote> InvoiceNotes { get; set; }

    }

}

AdventOne/Models/View/ChangeDate.cs
namespace AdventOne.Models.View {
    
    public class ChangeDate {

        public int ID { get; set; }
        public int Quantity { get; set; }
        public Period Period { get; set; }

    }
}

AdventOne/Models/WorkOrder.cs
namespace AdventOne.Models {

    public class WorkOrder {

        public int ID { get; set; }
        public string Description { get; set; }
        public int ProjectID { get; set; }

        public virtual Project Project { get; set; }

    }

}

AdventOne/Controllers/AttachmentController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdventOne.DAL;
using AdventOne.Models;
using AdventOne.Utils;

namespace AdventOne.Controllers {
    public class AttachmentController : BaseController
    {
        private ProjectContext db = new ProjectContext();

        // GET: Attachment
        public ActionResult Index()
        {
            base.SessionHandleIndexAction();
            var attachments = db.Attachments.Include(a => a.Project);
            return View(attachments.ToList());
        }

        // GET: Attachment/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            base.SessionHandleOtherActions();
            Attachment attachment = db.Attachments.Find(id);

            if (attachment == null) {
                return HttpNotFound();
            }
            return View(attachment);
        }

        // GET: Attachment/Create
        public ActionResult Create(int? projectId) {
            // ViewBag.CustomerId = new SelectList(db.Customers, "ID", "CustomerName");
            base.SessionHandleOtherActions();
            ViewBag.ProjectId = projectId;
            return View();
        }

        // POST: Attachment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Description,FileName,FileType,ContentType,ProjectId")] Attachment attachment, HttpPostedFileBase upload) {

            if (ModelState.IsValid) {

                attachment.FileName = System.IO.Path.GetFileName(upload.FileName);
                //Attachment avatar = null;
                //if (upload != null && upload.ContentLength > 0) {
                //    avatar = new Attachment 
                //        FileName = System.IO.Path.GetFileName(upload.FileName),
                //        FileType = FileType.Quotation,
                //        ContentType = upload.ContentType
                //    };
                //    using (var reader = new System.IO.BinaryReader(upload.InputStream)) {
                //        avatar.Content = reader.ReadBytes(upload.ContentLength);
                //    }

                using (var reader = new System.IO.BinaryReader(upload.InputStream)) {
                    attachment.Content = reader.ReadBytes(upload.ContentLength);
                }

                attachment.ContentType = MimeType.GetMimeMapping(upload.FileName);

                db.Attachments.Add(attachment);
                db.SaveChanges();
                return Redirect(base.SessionGetReturnURL());
            }

        

            return View();
        }

        // GET: Attachment/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            base.SessionHandleOtherActions();
            Attachment attachment = db.Attachments.Find(id);

            if (attachment == null)  {
                return HttpNotFound();
            }

            ViewBag.ProjectId = new SelectList(db.Projects, "ID", "ProjectName", attachment.ProjectId);
            return View(attachment);
        }

        // POST: Attachment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FileName,ContentType,Content,FileType,ProjectId")] Attachment attachment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(attachment).State = EntityState.Modified;
                db.SaveChanges();
                return Redirect(base.SessionGetReturnURL());
            }
            ViewBag.ProjectId = new SelectList(db.Projects, "ID", "ProjectName", attachment.ProjectId);
            return View(attachment);
        }

        // GET: Attachment/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            base.SessionHandleOtherActions();
            Attachment attachment = db.Attachments.Find(id);

            if (attachment == null) {
                return HttpNotFound();
            }

            return View(attachment);

        }

        // POST: Attachment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {
            Attachment attachment = db.Attachments.Find(id);
            db.Attachments.Remove(attachment);
            db.SaveChanges();
            return Redirect(base.SessionGetReturnURL());
        }

        public ActionResult Download(int id) {
            Attachment attachment = db.Attachments.Find(id);
            return File(attachment.Content, attachment.ContentType, attachment.FileName);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdventOne/Controllers/TaskController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AdventOne.DAL;
using AdventOne.Models;
using AdventOne.Models.View;

namespace AdventOne.Controllers {

    public class TaskController : BaseController {

        private ProjectContext db = new ProjectContext();

        // GET: Task
        public ActionResult Index() {
            var tasks = db.Tasks.Include(t => t.Project);
            return View(tasks.ToList());
        }

        // GET: Task/Details/5
        public ActionResult Details(int? id) {

            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            base.SessionHandleOtherActions();

            Task task = db.Tasks.Find(id);
            //task.PopulateFields();

            if (task == null) {
                return HttpNotFound();
            }

            return View(task);

        }

        // GET: Task/Create
        public ActionResult Create(int? projectId) {

            base.SessionHandleOtherActions();
            Project project = db.Projects.Find(projectId);
            ViewBag.Project = project;

            Task task = new Task();
            task.SalesStage = project.SalesStage;
            task.InvoiceDate = project.InvoiceDate;

            ViewBag.SupplierID = new SelectList(db.Suppliers, "ID", "SupplierName");
            return View(task);

        }

        // POST: Task/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ProjectID,Description,FullText,RevenueType,ProductQuantity,ProductUnitPrice,HourlyRate,ServicesQuantity,NumberOfHours,SalesStage,InvoiceDate,SupplierID")] Task task) {

            Project project = db.Projects.Find(task.ProjectID);

            // Handle different revenue types ..

            task.CalculateFields(project);

            ModelState.Remove("Quantity");
            ModelState.Remove("UnitPrice");
            ModelState.Remove("ExtendedPrice");

            if (ModelState.IsValid) {

                task.Sequence = project.Tasks.Count();
                db.Tasks.Add(task);
                db.SaveChanges();

                decimal revenue = 0M;
                decimal cos = 0M;
                decimal margin = 0M;

                foreach (Task newTask in project.Tasks) {

                    switch (newTask.RevenueType) {

                        case RevenueType.REV:
                        case RevenueType.SVC:
                            revenue += newTask.ExtendedPrice;
                            margin += newTask.ExtendedPrice;
                            break;

                        case RevenueType.COS:
                            cos += newTask.ExtendedPrice;
                            margin -= newTask.ExtendedPrice;
                            break;

                    }

                }

                project.Revenue = revenue;
                project.COS = cos;
                project.Margin = margin;
                db.SaveChanges();

                return Redirect(base.SessionGetReturnURL());
            }

            ViewBag.Project = project;
            ViewBag.SupplierID = new SelectList(db.Suppliers, "ID", "SupplierName", task.SupplierID);
            return View(task);

        }

        // GET: Task/Edit/5
        public ActionResult Edit(int? id) {

            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            base.SessionHandleOtherActions();
            Task task = db.Tasks.Find(id);

            if (task == null) {
                return HttpNotFound();
            }

            //task.PopulateFields();

            ViewBag.Project = task.Project;
            ViewBag.SupplierID = new SelectList(db.Suppliers, "ID", "SupplierName", task.SupplierID);

            return View(task);

        }

        // POST: Task/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ProjectID,Description,FullText,RevenueType,ProductQuantity,ProductUnitPrice,HourlyRate,ServicesQuantity,NumberOfHours,SalesStage,InvoiceDate,SupplierID")] Task task) {

            Project project = db.Projects.Find(task.ProjectID);


            // Handle different revenue types ..

            task.CalculateFields(project);

           //ModelState.Remove("Quantity");
            //ModelState.Remove("UnitPrice");
            //ModelState.Remove("ExtendedPrice");

            if (ModelState.IsValid) {

                db.Entry(task).State = EntityState.Modified;
                db.SaveChanges();

                decimal revenue = 0M;
                decimal cos = 0M;
                decimal margin = 0M;

                foreach (Task newTask in project.Tasks) {

                    switch (newTask.RevenueType) {

                        case RevenueType.REV:
                        case RevenueType.SVC:
                            revenue += newTask.ExtendedPrice;
                            margin += newTask.ExtendedPrice;
                            break;

                        case RevenueType.COS:
                            cos += newTask.ExtendedPrice;
                            margin -= newTask.ExtendedPrice;
                            break;

                    }

                }

                project.Revenue = revenue;
                project.COS = cos;
                project.Margin = margin;
                db.SaveChanges();

                return Redirect(base.SessionGetReturnURL());
            }

            ViewBag.Project = project;
            ViewBag.SupplierID = new SelectList(db.Suppliers, "ID", "SupplierName", task.SupplierID);
            return View(task);

        }

        // GET: Task/Delete/5
        public ActionResult Delete(int? id) {

            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            base.SessionHandleOtherActions();
            Task task = db.Tasks.Find(id);

            if (task == null) {
                return HttpNotFound();
            }
            return View(task);
        }

        // POST: Task/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {

            Task task = db.Tasks.Find(id);
            int sequence = task.Sequence;

            db.Tasks.Remove(task);
            db.SaveChanges();

            decimal revenue = 0M;
            decimal cos = 0M;
            decimal margin = 0M;
            Project project = db.Projects.Find(task.ProjectID);

            foreach (Task newTask in project.Tasks) {

                switch (newTask.RevenueType) {

                    case RevenueType.REV:
                    case RevenueType.SVC:
                        revenue += newTask.ExtendedPrice;
                        margin += newTask.ExtendedPrice;
                        break;

                    case RevenueType.COS:
                        cos += newTask.ExtendedPrice;
                        margin -= newTask.ExtendedPrice;
                        break;

                }

                if (newTask.Sequence > sequence) {

                    newTask.Sequence--;
                    newTask.CalculateFields(project);
                    db.Entry(newTask).State = EntityState.Modified;

                }

            }

            db.Configuration.ValidateOnSaveEnabled = false;
            db.SaveChanges();

            project.Revenue = revenue;
            project.COS = cos;
            project.Margin = margin;
            db.SaveChanges();

            return Redirect(base.SessionGetReturnURL());

        }

        // POST: Task/Delete/5
        [HttpPost, ActionName("Cancel")]
        [ValidateAntiForgeryToken]
        public ActionResult Cancel(string action, int id) {

            return Redirect(base.SessionGetReturnURL());

        }

        // GET: Task/MoveUp
        public ActionResult MoveUp(int projectId, int taskId) {

            Project project = db.Projects.Find(projectId);
            if (project == null) {
                return HttpNotFound();
            }

            Task taskToMove = db.Tasks.Find(taskId);
            if (project == null) {
                return HttpNotFound();
            }

            foreach (Task task in project.Tasks) {

                if (task.Sequence == taskToMove.Sequence - 1) {

                    task.Sequence = taskToMove.Sequence;
                    taskToMove.Sequence = task.Sequence - 1;
                    db.Configuration.ValidateOnSaveEnabled = false;
                    db.SaveChanges();

                }

            }

            return RedirectToAction("Details", "Project", new { id = projectId });

        }

        // GET: Task/MoveDown
        public ActionResult MoveDown(int projectId, int taskId) {

            Project project = db.Projects.Find(projectId);
            if (project == null) {
                return HttpNotFound();
            }

            Task taskToMove = db.Tasks.Find(taskId);
            if (project == null) {
                return HttpNotFound();
            }

            foreach (Task task in project.Tasks) {

                if (task.Sequence == taskToMove.Sequence + 1) {

                    task.Sequence = taskToMove.Sequence;
                    taskToMove.Sequence = task.Sequence + 1;
                    db.Configuration.ValidateOnSaveEnabled = false;
                    db.SaveChanges();
                    break;

AdventOne/Views/Project/Delete.cshtml
@using AdventOne.Models
@model AdventOne.Models.Project

<h2>Delete Project</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <table width="100%">
        <tr valign="top">
            <td>
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Employee)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Employee.EmployeeName)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Customer.CustomerName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Customer.CustomerName)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.ProjectName)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.ProjectName)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.InvoiceDate)
                    </dt>
                    <dd>
                        @Html.Raw(Model.InvoiceDate.ToString("dd/MM/yyyy"))
                    </dd>
                </dl>
            </td>
            <td>
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.SalesStage)
                    </dt>
                    <dd>
                        @Html.Raw(EnumHelpers.GetEnumDisplayName(Model.SalesStage))
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.ProjectStatus)
                    </dt>
                    <dd>
                        @Html.Raw(EnumHelpers.GetEnumDisplayName(Model.ProjectStatus))
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Division)
                    </dt>
                    <dd>
                        @Html.Raw(EnumHelpers.GetEnumDisplayName(Model.Division))
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Location)
                    </dt>
                    <dd>
                        @Html.Raw(EnumHelpers.GetEnumDisplayName(Model.Location))
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Branch)
                    </dt>
                    <dd>
                        @Html.Raw(EnumHelpers.GetEnumDisplayName(Model.Branch))
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.PaymentTerm)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.PaymentTerm.Description)
                    </dd>
                </dl>
            </td>
            <td>
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Revenue)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Revenue)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.COS)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.COS)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Margin)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Margin)
                    </dd>

                </dl>
            </td>
        </tr>
    </table>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />&nbsp;&nbsp;|&nbsp;&nbsp;
            <a href="@ViewBag.ReturnURL">
                <i class="fa fa-caret-square-o-left"></i>
            </a>
            @Html.ActionLink("Back to previous page", null, null, null, new { href = ViewBag.ReturnURL })
        </div>
    }
</div>

AdventOne/Views/Project/_Attachments.cshtml
@using AdventOne.Models
@model Project

<h3>
    @Html.DisplayNameFor(model => model.Attachments)
</h3>
<dd>
    <table class="table" width="100%">
        <tr>
            <th>Description</th>
            <th>File Type</th>
            <th></th>
        </tr>
        @foreach (var attachment in Model.Attachments) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => attachment.FileName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => attachment.FileType)
                </td>
                <td>
                    @Html.ActionLink(" ", "Download", "Attachment", new { id = attachment.ID }, new { @class = "fa fa-download", @style = "text-decoration:none;" })
                    @Html.ActionLink(" ", "Details", "Attachment", new { id = attachment.ID }, new { @class = "fa fa-search-plus", @style = "text-decoration:none;" })
                    @Html.ActionLink(" ", "Delete", "Attachment", new { id = attachment.ID }, new { @class = "fa fa-trash", @style = "text-decoration:none;" })
                </td>
            </tr>
        }
    </table>
    @Html.ActionLink(" ", "Create", "Attachment", new { projectId = Model.ID }, new { @class = "fa fa-plus-square", @style = "text-decoration:none;" })
    @Html.ActionLink("Create", "Create", "Attachment", new { projectId = Model.ID }, null)
    &nbsp;|&nbsp;
    @Html.ActionLink(" ", "RenderPDF", "Project", new { id = Model.ID }, new { @class = "fa fa-sticky-note", @style = "text-decoration:none;" })
    @Html.ActionLink("Generate Quote", "RenderPDF", "Project", new { id = Model.ID }, null)

</dd>

AdventOne/Views/Project/_ChangeDates.cshtml
@using AdventOne.Models
@using AdventOne.Models.View
@model ChangeDate


@using (Html.BeginForm()) {

    <div class="modal-content">

        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h4 class="modal-title" id="myModalLabel">Change Dates</h4>
        </div>
        
        <div class="modal-body">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)

            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
            <br />
            <br />
            @Html.LabelFor(model => model.Period, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Period, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Period, "", new { @class = "text-danger" })
            </div>
            <br />
            <br />
        </div>

        <div class="modal-footer">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default btn-primary" />
            </div>
        </div>


    </div>
}

AdventOne/Views/Project/_Invoices.cshtml
@using AdventOne.Models
@model Project

<h3>
    @Html.DisplayNameFor(model => model.Invoices)
</h3>
<dd>
    <table class="table" width="100%">
        <tr>
            <th>Invoice Number</th>
            <th>Amount</th>
            <th>Status</th>
            <th>Invoice Date</th>
            <th>Due Date</th>
            <th>Expected Payment</th>
            <th>Days Overdue</th>
            <th></th>
        </tr>
        @foreach (var invoice in Model.Invoices) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => invoice.InvoiceNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => invoice.Amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => invoice.Status)
        </td>
        <td>
            @Html.Raw(invoice.InvoiceDate.ToString("dd/MM/yyyy"))
        </td>
        <td>
            @Html.Raw(invoice.DueDate.ToString("dd/MM/yyyy"))
        </td>
        <td>
            @Html.Raw(invoice.ExpectedPaymentDate.ToString("dd/MM/yyyy"))
        </td>
        <td>
            @Html.Raw(invoice.DaysOverdue)
        </td>
        <td>
            @Html.ActionLink(" ", "Edit", "Invoice", new { id = invoice.ID }, new { @class = "fa fa-edit", @style = "text-decoration:none;" })
            @Html.ActionLink(" ", "Details", "Invoice", new { id = invoice.ID }, new { @class = "fa fa-search-plus", @style = "text-decoration:none;" })
            @Html.ActionLink(" ", "Delete", "Invoice", new { id = invoice.ID }, new { @class = "fa fa-trash", @style = "text-decoration:none;" })
        </td>
    </tr>
        }
    </table>
    @Html.ActionLink(" ", "Create", "Invoice", new { projectId = Model.ID }, new { @class = "fa fa-plus-square", @style = "text-decoration:none;" })
    @Html.ActionLink("Create", "Create", "Invoice", new { projectId = Model.ID }, null)

</dd>

AdventOne/Views/Project/_Tasks.cshtml
@using AdventOne.Models
@model Project

<h3>
    @Html.DisplayNameFor(model => model.Tasks)
</h3>
<dd>
    <table class="table" width="100%">
        <tr>
            <td>Description</td>
            <td>Revenue Type</td>
            <td>Invoice Date</td>
            <td>Quantity</td>
            <td>Unit Amount</td>
            <td>Extended Amount</td>
            <td></td>
        </tr>
        @for (int i = 0; i < Model.Tasks.Count(); i++) {
            var task = Model.Tasks.ToList()[i];
    <tr>
        <td>
            @Html.DisplayFor(modelItem => task.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => task.RevenueType)
        </td>
        <td>
            @Html.Raw(task.InvoiceDate.ToString("dd/MM/yyyy"))
        </td>
        <td>
            @Html.DisplayFor(modelItem => task.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => task.UnitPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => task.ExtendedPrice)
        </td>
        <td>
            @Html.ActionLink(" ", "Edit", "Task", new { id = task.ID }, new { @class = "fa fa-edit fa-10x", @style = "text-decoration:none;" })
            @Html.ActionLink(" ", "Details", "Task", new { id = task.ID }, new { @class = "fa fa-search-plus", @style = "text-decoration:none;" })
            @Html.ActionLink(" ", "Delete", "Task", new { id = task.ID }, new { @class = "fa fa-trash", @style = "text-decoration:none;" })
            &nbsp;|&nbsp;
            <a href="javascript:void(0);" class="duplicate" data-id="@task.ID">
                <i class="fa fa-copy"></i>
            </a>
            @if (i > 0) {
                @Html.ActionLink(" ", "MoveUp", "Task", new { projectId = Model.ID, taskId = task.ID }, new { @class = "fa fa-arrow-circle-up fa-10x", @style = "text-decoration:none;" })
            }
            else {
                @:&nbsp;&nbsp;&nbsp;
            }
            @if (i < Model.Tasks.Count() - 1) {
                @Html.ActionLink(" ", "MoveDown", "Task", new { projectId = Model.ID, taskId = task.ID }, new { @class = "fa fa-arrow-circle-down fa-10x", @style = "text-decoration:none;" })
            }
        </td>
    </tr>
        }
    </table>
    @Html.ActionLink(" ", "Create", "Task", new { projectId = Model.ID }, new { @class = "fa fa-plus-square", @style = "text-decoration:none;" })
    @Html.ActionLink("Create", "Create", "Task", new { projectId = Model.ID }, null)

</dd>

<div id='modalDuplicate' class='modal'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='modalDuplicateContent'></div>
        </div>
    </div>

</div>

<script>
    var TeamDetailPostBackURL = '/Task/Duplicate';
    $(function () {
        $(".duplicate").click(function () {
            var $buttonClicked = $(this);
            var id = $buttonClicked.attr('data-id');
            var options = { "backdrop": "static", keyboard: true };
            $.ajax({
                type: "GET",
                url: TeamDetailPostBackURL,
                contentType: "application/json; charset=utf-8",
                data: { "Id": id },
                datatype: "json",
                success: function (data) {
                    debugger;
                    $('#modalDuplicateContent').html(data);
                    $('#modalDuplicate').modal(options);
                    $('#modalDuplicate').modal('show');

                },
                error: function () {
                    alert("Dynamic content load failed.");
                }
            });
        });

        $("#closbtn").click(function () {
            $('#modalDuplicate').modal('hide');
        });
    });

</script>