AdventOne/Models/WorkOrder.cs
namespace AdventOne.Models {

    public class WorkOrder {

        public int ID { get; set; }
        public string Description { get; set; }
        public int ProjectID { get; set; }

        public virtual Project Project { get; set; }

    }

}

AdventOne/Controllers/WorkOrderController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AdventOne.Controllers;
using AdventOne.DAL;
using AdventOne.Models;

namespace AdventOne.Views {

    public class WorkOrderController : BaseController {

        private ProjectContext db = new ProjectContext();

        // GET: WorkOrder
        public ActionResult Index() {
            var workOrders = db.WorkOrders.Include(w => w.Project);
            return View(workOrders.ToList());
        }

        // GET: WorkOrder/Details/5
        public ActionResult Details(int? id) {

            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            base.SessionHandleOtherActions();

            WorkOrder workOrder = db.WorkOrders.Find(id);

            if (workOrder == null) {
                return HttpNotFound();
            }

            return View(workOrder);

        }

        // GET: WorkOrder/Create
        public ActionResult Create(int? projectId) {

            base.SessionHandleOtherActions();
            ViewBag.ProjectID = projectId;
            return View();

        }

        // POST: WorkOrder/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Description,ProjectID")] WorkOrder workOrder) {
            if (ModelState.IsValid) {
                db.WorkOrders.Add(workOrder);
                db.SaveChanges();
                return Redirect(base.SessionGetReturnURL()); 
            }

            ViewBag.ProjectID = new SelectList(db.Projects, "ID", "ProjectName", workOrder.ProjectID);
            return View(workOrder);
        }

        // GET: WorkOrder/Edit/5
        public ActionResult Edit(int? id) {

            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            base.SessionHandleOtherActions();
            WorkOrder workOrder = db.WorkOrders.Find(id);

            if (workOrder == null) {
                return HttpNotFound();
            }

            ViewBag.ProjectID = workOrder.Project.ID;
            return View(workOrder);
        }

        // POST: WorkOrder/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Description,ProjectID")] WorkOrder workOrder) {
            if (ModelState.IsValid) {
                db.Entry(workOrder).State = EntityState.Modified;
                db.SaveChanges();
                return Redirect(base.SessionGetReturnURL());
            }
            ViewBag.ProjectID = new SelectList(db.Projects, "ID", "ProjectName", workOrder.ProjectID);
            return View(workOrder);
        }

        // GET: WorkOrder/Delete/5
        public ActionResult Delete(int? id) {

            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            base.SessionHandleOtherActions();
            WorkOrder workOrder = db.WorkOrders.Find(id);

            if (workOrder == null) {
                return HttpNotFound();
            }

            return View(workOrder);

        }

        // POST: WorkOrder/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {
            WorkOrder workOrder = db.WorkOrders.Find(id);
            db.WorkOrders.Remove(workOrder);
            db.SaveChanges();
            return Redirect(base.SessionGetReturnURL());
        }

        protected override void Dispose(bool disposing) {
            if (disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdventOne/Views/WorkOrder/Create.cshtml
@model AdventOne.Models.WorkOrder

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>WorkOrder</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.Hidden("projectId", (object)ViewBag.ProjectId)

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    <a href="@ViewBag.ReturnURL">
        <i class="fa fa-caret-square-o-left"></i>
    </a>
    @Html.ActionLink("Back to previous page", null, null, null, new { href = ViewBag.ReturnURL })
</div>

AdventOne/Views/WorkOrder/Delete.cshtml
@model AdventOne.Models.WorkOrder

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WorkOrder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Project.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AdventOne/Views/WorkOrder/Details.cshtml
@model AdventOne.Models.WorkOrder

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>WorkOrder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Project.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink(" ", "Edit", "WorkOrder", new { id = Model.ID }, new { @class = "fa fa-edit fa-10x", @style = "text-decoration:none;" })
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID })&nbsp;&nbsp;|&nbsp;
    <a href="@ViewBag.ReturnURL">
        <i class="fa fa-caret-square-o-left"></i>
    </a>
    @Html.ActionLink("Back to previous page", null, null, null, new { href = ViewBag.ReturnURL })
</p>

AdventOne/Views/WorkOrder/Edit.cshtml
@model AdventOne.Models.WorkOrder

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>WorkOrder</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)
    @Html.Hidden("projectId", (object)ViewBag.ProjectId)

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    <a href="@ViewBag.ReturnURL">
        <i class="fa fa-caret-square-o-left"></i>
    </a>
    @Html.ActionLink("Back to previous page", null, null, null, new { href = ViewBag.ReturnURL })
</div>

AdventOne/Views/WorkOrder/Index.cshtml
@model IEnumerable<AdventOne.Models.WorkOrder>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Project.ProjectName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Project.ProjectName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>