AdventOne/Models/InvoiceNote.cs
using System;

namespace AdventOne.Models {

    public class InvoiceNote {

        public int ID { get; set; }
        public int InvoiceID { get; set; }
        public int EmployeeID { get; set; }

        public String Notes { get; set; }

        public DateTime CreatedDate { get; set; }
        public DateTime OriginalExpectedPaymentDate { get; set; }
        public DateTime RevisedExpectedPaymentDate { get; set; }

        public virtual Invoice Invoice { get; set; }
        public virtual Employee Employee { get; set; }

    }

}

AdventOne/Controllers/InvoiceNoteController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdventOne.DAL;
using AdventOne.Models;

namespace AdventOne.Controllers {

    public class InvoiceNoteController : BaseController {

        private ProjectContext db = new ProjectContext();

        // GET: InvoiceNote
        public ActionResult Index() {

            base.SessionHandleIndexAction();

            var invoiceNotes = db.InvoiceNotes.Include(i => i.Invoice);
            return View(invoiceNotes.ToList());
        }

        // GET: InvoiceNote/Details/5
        public ActionResult Details(int? id) {

            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            base.SessionHandleOtherActions();
            InvoiceNote invoiceNote = db.InvoiceNotes.Find(id);

            if (invoiceNote == null) {
                return HttpNotFound();
            }

            return View(invoiceNote);

        }

        // GET: InvoiceNote/Create
        public ActionResult Create(int? invoiceId) {

            base.SessionHandleOtherActions();

            Invoice invoice = db.Invoices.Find(invoiceId);
            ViewBag.Invoice = invoice;
            return View();

        }

        // POST: InvoiceNote/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,InvoiceID,Notes,OriginalExpectedPaymentDate,RevisedExpectedPaymentDate")] InvoiceNote invoiceNote) {

            if (ModelState.IsValid) {

                Invoice invoice = db.Invoices.Find(invoiceNote.InvoiceID);

                HttpSessionStateBase session = HttpContext.Session;
                Employee employee = (Employee)session["employee"];

                invoiceNote.CreatedDate = DateTime.Now;
                invoiceNote.Employee = employee;

                db.InvoiceNotes.Add(invoiceNote);
                db.SaveChanges();


                // Update invoice as well .

                invoice.ExpectedPaymentDate = invoiceNote.RevisedExpectedPaymentDate;

                if (invoice.Status == InvoiceStatus.Open) {
                    invoice.DaysOverdue = ((int)(invoice.ExpectedPaymentDate - invoice.DueDate).Days);
                }
                else {
                    invoice.DaysOverdue = 0;
                }

                db.Entry(invoice).State = EntityState.Modified;
                db.SaveChanges();

                return Redirect(base.SessionGetReturnURL());
            }

            ViewBag.InvoiceID = new SelectList(db.Invoices, "ID", "InvoiceNumber", invoiceNote.InvoiceID);
            return View(invoiceNote);

        }

        // GET: InvoiceNote/Edit/5
        public ActionResult Edit(int? id) {

            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            base.SessionHandleOtherActions();
            InvoiceNote invoiceNote = db.InvoiceNotes.Find(id);

            if (invoiceNote == null) {
                return HttpNotFound();
            }

            ViewBag.InvoiceID = invoiceNote.InvoiceID;
            return View(invoiceNote);

        }

        // POST: InvoiceNote/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,InvoiceID,Notes,OriginalExpectedPaymentDate,RevisedExpectedPaymentDate,CreatedDate,EmployeeId")] InvoiceNote invoiceNote) {
            if (ModelState.IsValid) {

                Invoice invoice = db.Invoices.Find(invoiceNote.InvoiceID);

                db.Entry(invoiceNote).State = EntityState.Modified;
                db.SaveChanges();


                // Update invoice as well .

                invoice.ExpectedPaymentDate = invoiceNote.RevisedExpectedPaymentDate;

                if (invoice.Status == InvoiceStatus.Open) {
                    invoice.DaysOverdue = ((int)(invoice.ExpectedPaymentDate - invoice.DueDate).Days);
                }
                else {
                    invoice.DaysOverdue = 0;
                }

                db.Entry(invoice).State = EntityState.Modified;
                db.SaveChanges();

                return Redirect(base.SessionGetReturnURL());
            }
            ViewBag.InvoiceID = new SelectList(db.Invoices, "ID", "InvoiceNumber", invoiceNote.InvoiceID);
            return View(invoiceNote);
        }

        // GET: InvoiceNote/Delete/5
        public ActionResult Delete(int? id) {

            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            base.SessionHandleOtherActions();
            InvoiceNote invoiceNote = db.InvoiceNotes.Find(id);

            if (invoiceNote == null) {
                return HttpNotFound();
            }

            return View(invoiceNote);

        }

        // POST: InvoiceNote/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {

            InvoiceNote invoiceNote = db.InvoiceNotes.Find(id);
            db.InvoiceNotes.Remove(invoiceNote);
            db.SaveChanges();

            return Redirect(base.SessionGetReturnURL());

        }

        protected override void Dispose(bool disposing) {
            if (disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdventOne/Views/InvoiceNote/Create.cshtml
@model AdventOne.Models.InvoiceNote

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>InvoiceNote</h4>
    <hr />
    @Html.Hidden("invoiceID", (object)ViewBag.Invoice.ID)
    @Html.Hidden("originalExpectedPaymentDate", (object)ViewBag.Invoice.ExpectedPaymentDate)
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OriginalExpectedPaymentDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.Raw(ViewBag.Invoice.ExpectedPaymentDate.ToString("dd/MM/yyy"))
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RevisedExpectedPaymentDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RevisedExpectedPaymentDate,
               new {
                        htmlAttributes = new {
                 @Value = DateTime.Now.ToString("dd/MM/yyyy"),
                 @class = "form-control"
                        },
                    })
            @Html.ValidationMessageFor(model => model.RevisedExpectedPaymentDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    <p>
        <a href="@ViewBag.ReturnURL">
            <i class="fa fa-caret-square-o-left"></i>
        </a>
        @Html.ActionLink("Back to previous page", null, null, null, new { href = ViewBag.ReturnURL })
    </p>
</div>

@section scripts {

    <script type="text/javascript">

  $(function () {

    $('#RevisedExpectedPaymentDate').datetimepicker({
        format: 'DD/MM/YYYY',
        
      showClose: true,
      showClear: true,
      showTodayButton: true,
      toolbarPlacement: 'top'
    });
      
  });

    </script>

}

AdventOne/Views/InvoiceNote/Delete.cshtml
@model AdventOne.Models.InvoiceNote

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>InvoiceNote</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Invoice.InvoiceNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Invoice.InvoiceNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OriginalExpectedPaymentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OriginalExpectedPaymentDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RevisedExpectedPaymentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RevisedExpectedPaymentDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />&nbsp;&nbsp;|&nbsp;
            <a href="@ViewBag.ReturnURL">
                <i class="fa fa-caret-square-o-left"></i>
            </a>
            @Html.ActionLink("Back to previous page", null, null, null, new { href = ViewBag.ReturnURL })
        </div>
    }
</div>

AdventOne/Views/InvoiceNote/Details.cshtml
@model AdventOne.Models.InvoiceNote

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>InvoiceNote</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Invoice.InvoiceNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Invoice.InvoiceNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OriginalExpectedPaymentDate)
        </dt>

        <dd>
            @Html.Raw(Model.OriginalExpectedPaymentDate.ToString("dd/MM/yyyy"))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RevisedExpectedPaymentDate)
        </dt>

        <dd>
            @Html.Raw(Model.RevisedExpectedPaymentDate.ToString("dd/MM/yyyy"))
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink(" ", "Edit", "InvoiceNote", new { id = Model.ID }, new { @class = "fa fa-edit", @style = "text-decoration:none;" })
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID })&nbsp;&nbsp;|&nbsp;
    <a href="@ViewBag.ReturnURL">
        <i class="fa fa-caret-square-o-left"></i>
    </a>
    @Html.ActionLink("Back to previous page", null, null, null, new { href = ViewBag.ReturnURL })

</p>

AdventOne/Views/InvoiceNote/Edit.cshtml
@model AdventOne.Models.InvoiceNote

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>InvoiceNote</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)
    @Html.HiddenFor(model => model.InvoiceID)
    @Html.HiddenFor(model => model.CreatedDate)
    @Html.HiddenFor(model => model.EmployeeID)

    <div class="form-group">
        @Html.LabelFor(model => model.Invoice.InvoiceNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.Raw(Model.Invoice.InvoiceNumber)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OriginalExpectedPaymentDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.Raw(Model.OriginalExpectedPaymentDate.ToString("dd/MM/yyyy"))
            @Html.Hidden("originalExpectedPaymentDate", Model.OriginalExpectedPaymentDate)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RevisedExpectedPaymentDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RevisedExpectedPaymentDate,
               new {
                        htmlAttributes = new {
                 @Value = Model.RevisedExpectedPaymentDate.ToString("dd/MM/yyyy"),
                 @class = "form-control"
                        },
                    })
            @Html.ValidationMessageFor(model => model.RevisedExpectedPaymentDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    <a href="@ViewBag.ReturnURL">
        <i class="fa fa-caret-square-o-left"></i>
    </a>
    @Html.ActionLink("Back to previous page", null, null, null, new { href = ViewBag.ReturnURL })
</div>

@section scripts {

    <script type="text/javascript">

        $(function () {

            $('#RevisedExpectedPaymentDate').datetimepicker({
                format: 'DD/MM/YYYY',
                showClose: true,
                showClear: true,
                showTodayButton: true,
                toolbarPlacement: 'top'
            });

        });

    </script>

}

AdventOne/Views/InvoiceNote/Index.cshtml
@model IEnumerable<AdventOne.Models.InvoiceNote>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink(" ", "Create", "InvoiceNote", new { }, new { @class = "fa fa-plus-square", @style = "text-decoration:none;" })
    @Html.ActionLink("Create", "Create", "InvoiceNote", new { }, null)
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Invoice.InvoiceNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Notes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OriginalExpectedPaymentDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RevisedExpectedPaymentDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Invoice.InvoiceNumber)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Notes)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CreatedDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.OriginalExpectedPaymentDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.RevisedExpectedPaymentDate)
    </td>
    <td>
        @Html.ActionLink(" ", "Edit", "InvoiceNote", new { id = item.ID }, new { @class = "fa fa-edit fa-10x", @style = "text-decoration:none;" })
        @Html.ActionLink(" ", "Details", "InvoiceNote", new { id = item.ID }, new { @class = "fa fa-search-plus", @style = "text-decoration:none;" })
        @Html.ActionLink(" ", "Delete", "InvoiceNote", new { id = item.ID }, new { @class = "fa fa-trash", @style = "text-decoration:none;" })
    </td>
</tr>
}

</table>